"""drop duplicate city index

Revision ID: 96298b54cb53
Revises: d27abda87973
Create Date: 2025-11-04 23:24:50.054168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96298b54cb53'
down_revision: Union[str, Sequence[str], None] = 'd27abda87973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_city'), table_name='stations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_station_city'), 'stations', ['city'], unique=False)
    # ### end Alembic commands ###
