"""init tables

Revision ID: d27abda87973
Revises: 
Create Date: 2025-11-04 23:05:11.603215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27abda87973'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_station_source_extid')
    )
    op.create_index('ix_station_city', 'stations', ['city'], unique=False)
    op.create_index(op.f('ix_stations_city'), 'stations', ['city'], unique=False)
    op.create_index(op.f('ix_stations_external_id'), 'stations', ['external_id'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.Enum('pm25', 'pm10', 'no2', 'o3', name='parameter_enum'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'parameter', 'measured_at', name='uq_station_param_time')
    )
    op.create_index(op.f('ix_measurements_measured_at'), 'measurements', ['measured_at'], unique=False)
    op.create_index(op.f('ix_measurements_parameter'), 'measurements', ['parameter'], unique=False)
    op.create_index(op.f('ix_measurements_station_id'), 'measurements', ['station_id'], unique=False)
    op.create_index('ix_param_measured_at', 'measurements', ['parameter', 'measured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_param_measured_at', table_name='measurements')
    op.drop_index(op.f('ix_measurements_station_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_parameter'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_measured_at'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_stations_external_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_city'), table_name='stations')
    op.drop_index('ix_station_city', table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
